name: Man Page Converter

on:
    push:
        paths:
          - 'man/*.md'
          - 'fabtests/man/*.md'
    workflow_dispatch:

jobs:
    nroff-elves-scheduled:
        name: The Nroff Elves
        runs-on: ubuntu-latest
        permissions:
          contents: write
          pull-requests: write
        steps:
          - name: Debug information
            env:
              GITHUB_DATA: ${{ toJSON(github) }}
            run: |
              echo This is information that may be useful for debugging.
              echo "$GITHUB_DATA"

          - name: Check out the git repo
            uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

          - name: Get the required packages
            run: sudo apt install -y pandoc

          - name: Build the nroff man pages
            run: .github/workflows/nroff-elves.sh
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              REPO: ${{ github.event.repository.full_name }}
              BASE_REF: ${{ github.ref_name }}
